# BrowserPreferencePage
GENERAL_WEBBROWSER_URL=
BROWSER_SHOW_URL_BAR=true

# ContactFormatPreferencePage
# data.default.contact.format.salutation
CONTACT_FORMAT_GREETING_COMMON=%CONTACT_FORMAT_GREETING_COMMON Dear Sir or Madam
CONTACT_FORMAT_GREETING_COMPANY=%CONTACT_FORMAT_GREETING_COMMON

# data.default.contact.format.salutation.men
CONTACT_FORMAT_GREETING_MR=%CONTACT_FORMAT_GREETING_MR Dear Mr. {firstname} {lastname}

# data.default.contact.format.salutation.women
CONTACT_FORMAT_GREETING_MS=%CONTACT_FORMAT_GREETING_MS Dear Ms. {firstname} {lastname}

CONTACT_FORMAT_ADDRESS={company}<br>{title} {firstname} {lastname}<br>{street}<br>{countrycode}{zip} {city}<br>{country}

# data.default.contact.format.excludedcountries
CONTACT_FORMAT_HIDE_COUNTRIES=%CONTACT_FORMAT_HIDE_COUNTRIES USA,U.S.A.

# ContactPreferencePage
CONTACT_USE_DELIVERY=true
CONTACT_USE_MISC=true
CONTACT_USE_NOTE=true
CONTACT_USE_GENDER=true
CONTACT_NAME_FORMAT=0
CONTACT_USE_COMPANY=true
CONTACT_USE_COUNTRY=true

# DocumentPreferencePage
# com.sebulli.fakturama.dto.DocumentSummary.ROUND_GROSS_VALUES
DOCUMENT_USE_NET_GROSS=2
DOCUMENT_IMMEDIATELY_OVERTAKE_ITEMNUMBER_FROM_PRODUCTS_DIALOG=true
DOCUMENT_USE_PREVIEW_PICTURE=true
DOCUMENT_USE_DISCOUNT_EACH_ITEM=true
DOCUMENT_USE_DISCOUNT_ALL_ITEMS=true
DOCUMENT_DELIVERY_NOTE_ITEMS_WITH_PRICE=true
DOCUMENT_ADD_NR_OF_IMPORTED_DELIVERY_NOTE=true
DOCUMENT_CUSTOMER_STATISTICS_DIALOG=true
DOCUMENT_CUSTOMER_STATISTICS_COMPARE_ADDRESS_FIELD=1
DOCUMENT_MESSAGES=1

# preferences.document.label.depositrow
DOCUMENT_DEPOSIT_TEXT=%DOCUMENT_DEPOSIT_TEXT Text in the deposit row

# preferences.document.label.finalrow
DOCUMENT_FINALPAYMENT_TEXT=%DOCUMENT_FINALPAYMENT_TEXT Text in the final payment row

# ExportPreferencePage
EXPORTSALES_PAIDDATE=true

# GeneralPreferencePage
GENERAL_HAS_THOUSANDS_SEPARATOR=true
GENERAL_CURRENCY_DECIMALPLACES=2
GENERAL_QUANTITY_DECIMALPLACES=2
CURRENCY_USE_SYMBOL=SYMBOL
# TODO: PREFERENCE_CURRENCY_LOCALE???
PREFERENCE_CURRENCY_LOCALE=de_DE
PREFERENCES_GENERAL_KEEP_NUMBER_BACKUPS=10

# NumberRangeFormatPreferencePage
# preferences.numberrange.format.debitorno.value
NUMBERRANGE_DEBITOR_FORMAT=%NUMBERRANGE_DEBITOR_FORMAT CUST{6nr}

# preferences.numberrange.format.creditorno.value
NUMBERRANGE_CREDITOR_FORMAT=%NUMBERRANGE_CREDITOR_FORMAT CRD{6nr}

# preferences.numberrange.format.invoiceno.value
NUMBERRANGE_INVOICE_FORMAT=%NUMBERRANGE_INVOICE_FORMAT INV{6nr}

# preferences.numberrange.format.deliverynoteno.value
NUMBERRANGE_DELIVERY_FORMAT=%NUMBERRANGE_DELIVERY_FORMAT D/O{6nr}

# preferences.numberrange.format.offerno.value
NUMBERRANGE_OFFER_FORMAT=%NUMBERRANGE_OFFER_FORMAT LO{6nr}

# preferences.numberrange.format.orderno.value
NUMBERRANGE_ORDER_FORMAT=%NUMBERRANGE_ORDER_FORMAT PO{6nr}

# preferences.numberrange.format.creditno.value
NUMBERRANGE_CREDIT_FORMAT=%NUMBERRANGE_CREDIT_FORMAT IC{6nr}

# preferences.numberrange.format.confirmationo.value
NUMBERRANGE_CONFIRMATION_FORMAT=%NUMBERRANGE_CONFIRMATION_FORMAT CONF{6nr}

# preferences.numberrange.format.dunningno.value
NUMBERRANGE_DUNNING_FORMAT=%NUMBERRANGE_DUNNING_FORMAT DUNNING{6nr}

# preferences.numberrange.format.proformano.value
NUMBERRANGE_PROFORMA_FORMAT=%NUMBERRANGE_PROFORMA_FORMAT PROFORMA{6nr}

# NumberRangeValuesPreferencePage
NUMBERRANGE_DEBTOR_NR=1
NUMBERRANGE_CREDITOR_NR=1
NUMBERRANGE_PRODUCT_NR=1
NUMBERRANGE_INVOICE_NR=1
NUMBERRANGE_DELIVERY_NR=1
NUMBERRANGE_OFFER_NR=1
NUMBERRANGE_ORDER_NR=1
NUMBERRANGE_CREDIT_NR=1
NUMBERRANGE_CONFIRMATION_NR=1
NUMBERRANGE_DUNNING_NR=1
NUMBERRANGE_PROFORMA_NR=1

# OfficePreferencePage
OPENOFFICE_ODT_PATH_FORMAT=ODT/{yyyy}/{doctype}/{docname}_{address}.odt
OPENOFFICE_PDF_PATH_FORMAT=PDF/{yyyy}/{doctype}/{docname}_{address}.pdf
OPENOFFICE_START_IN_NEW_THREAD=true
# TODO: OPENOFFICE_PATH???

# OptionalItemsPreferencePage
OPTIONALITEMS_REPLACE_PRICE=true
OPTIONALITEMS_PRICE_REPLACEMENT=---

# preferences.optionalitems.itemlabel
OPTIONALITEMS_OPTIONALITEM_TEXT=%OPTIONALITEMS_OPTIONALITEM_TEXT Optional Item:<br>

# ProductPreferencePage
PRODUCT_USE_ITEMNR=true
PRODUCT_USE_DESCRIPTION=true
PRODUCT_USE_NET_GROSS=2
PRODUCT_SCALED_PRICES=1
PRODUCT_USE_VAT=true
PRODUCT_USE_QUANTITY=true
PRODUCT_CHANGE_QTY=2
PRODUCT_USE_PICTURE=true

# ToolbarPreferencePage
TOOLBAR_SHOW_WEBSHOP=true
TOOLBAR_SHOW_PRINT=true
TOOLBAR_SHOW_SAVE=true
TOOLBAR_SHOW_DOCUMENT_NEW_INVOICE=true
TOOLBAR_SHOW_DOCUMENT_NEW_OFFER=true
TOOLBAR_SHOW_DOCUMENT_NEW_DELIVERY=true
TOOLBAR_SHOW_NEW_PRODUCT=true
TOOLBAR_SHOW_NEW_CONTACT=true
TOOLBAR_SHOW_NEW_EXPENDITUREVOUCHER=true
TOOLBAR_SHOW_NEW_RECEIPTVOUCHER=true
TOOLBAR_SHOW_OPEN_BROWSER=true
TOOLBAR_SHOW_OPEN_CALCULATOR=true
TOOLBAR_SHOW_QRK_EXPORT=true

# WebShopAuthorizationPreferencePage
WEBSHOP_AUTHORIZATION_USER=user
WEBSHOP_AUTHORIZATION_PASSWORD=password

# WebShopImportPreferencePage
WEBSHOP_ENABLED=true

# preferences.webshop.defaulturl
WEBSHOP_URL=https://shop.fakturama.info/admin/fakturama2_connector.php
WEBSHOP_USER=user
WEBSHOP_PASSWORD=password

# preferences.webshop
WEBSHOP_PRODUCT_CATEGORY=%WEBSHOP_PRODUCT_CATEGORY Shop

# preferences.webshop.customer
WEBSHOP_CONTACT_CATEGORY=%WEBSHOP_CONTACT_CATEGORY Shop Customer

# preferences.webshop
WEBSHOP_SHIPPING_CATEGORY=%WEBSHOP_SHIPPING_CATEGORY Shop
WEBSHOP_NOTIFY_SHIPPED=true
WEBSHOP_MAX_PRODUCTS=1000