<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <name>ZUGFeRD PDF/A-3-Manager</name>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sebulli.fakturama</groupId>
        <artifactId>Fakturama-Parent</artifactId>
        <version>2.2.0-SNAPSHOT</version>
    </parent>
    <artifactId>org.fakturama.exporter.zugferd</artifactId>
    <packaging>eclipse-plugin</packaging>
    <description>This module manages the PDF/A3 conversion for ZUGFeRD. It
        includes the combining of an ZUGFeRD-invoice.xml file and a PDF/A-1
        document into a PDF/A-3 document. Furthermore, it includes an extractor
        which can extract the ZUGFeRD-invoice.xml from a valid PDF/A-3 document.</description>

    <properties>


    </properties>
    <build>
        <sourceDirectory>src</sourceDirectory>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <excludes>
                    <exclude>**/*.java</exclude>
                </excludes>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>build-helper-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>add-source</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>add-source</goal>
                        </goals>
                        <configuration>
                            <sources>
                                <source>
                                    ${project.build.directory}/src-gen/main/java/</source>
                            </sources>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.cxf</groupId>
                <artifactId>cxf-xjc-plugin</artifactId>
                <version>${cxf-xjc-plugin.version}</version>
                <configuration>
                    <extensions>
                        <extension>
                            org.apache.cxf.xjcplugins:cxf-xjc-dv:${cxf-xjc-plugin.version}</extension>
                    </extensions>
                </configuration>
                <executions>
                    <execution>
                        <id>xjc</id>
                        <phase>generate-sources</phase>
                        <goals>
                            <goal>xsdtojava</goal>
                        </goals>
                        <configuration>
                            <sourceRoot>
                                ${project.build.directory}/src-gen/main/java
                            </sourceRoot>
                            <xsdOptions>

                                <xsdOption>
                                    <xsd>
                                        ${project.basedir}/src/main/resources/zugpferd/Factur-X_1.07.2_EXTENDED.xsd</xsd>
                                    <bindingFile>
                                        ${project.basedir}/src/main/resources/zugpferd/invoice.xjb</bindingFile>
                                    <packagename>
                                        org.fakturama.export.facturx.modelgen</packagename>
                                    <extensionArgs>
                                        <!--<extensionArg>-Xts</extensionArg>-->
                                        <extensionArg>-npa</extensionArg>
                                    </extensionArgs>
                                </xsdOption>
                            </xsdOptions>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>


    </build>
    <!-- To use the report goals in your POM or parent POM -->
    <reporting>
        <plugins>
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>findbugs-maven-plugin</artifactId>
                <version>3.0.4-SNAPSHOT</version>
            </plugin>
        </plugins>
    </reporting>
    <dependencies>
        <dependency>
            <groupId>com.sebulli.fakturama</groupId>
            <artifactId>com.sebulli.fakturama.rcp</artifactId>
            <version>2.2.0-SNAPSHOT</version>
        </dependency>
    </dependencies>
</project>