#!/usr/bin/env bash
#
# Installed wrapper for the Fakturama2 Demo .deb package. App + JRE are already
# unpacked under /opt/fakturama2-demo/ (done once at package install time, not
# per run) - this script only does the per-run part that fakturama-demo.sh's
# generated body does after extraction: fresh temp workspace, DB password
# prompt, launch, cleanup on exit. Same behavior every run, no lasting state
# outside the package itself.
#
# Generated by build-demo-deb.sh from deb-wrapper-template.sh - not meant to be
# edited by hand on an installed system; rebuild the .deb instead.

set -euo pipefail

APP_DIR="/opt/fakturama2-demo/app"
JRE_DIR="/opt/fakturama2-demo/jre"

DB_HOST="__DB_HOST__"
DB_PORT="__DB_PORT__"
DB_NAME="__DB_NAME__"
DB_USER="__DB_USER__"
WEBBROWSER_URL="__WEBBROWSER_URL__"

prompt_password() {
    if command -v zenity >/dev/null 2>&1; then
        zenity --password --title="Fakturama Demo" \
            --text="Datenbank-Passwort für ${DB_USER}@${DB_HOST}:${DB_PORT}/${DB_NAME}:" 2>/dev/null
        return
    fi
    if command -v kdialog >/dev/null 2>&1; then
        kdialog --password "Datenbank-Passwort für ${DB_USER}@${DB_HOST}:${DB_PORT}/${DB_NAME}:" 2>/dev/null
        return
    fi
    read -r -s -p "Datenbank-Passwort für ${DB_USER}@${DB_HOST}:${DB_PORT}/${DB_NAME}: " pw >&2
    echo >&2
    printf '%s' "$pw"
}

DB_PASSWORD="$(prompt_password || true)"
if [ -z "$DB_PASSWORD" ]; then
    echo "Kein Passwort eingegeben, breche ab." >&2
    exit 1
fi

WORKDIR="$(mktemp -d /tmp/fakturama-demo.XXXXXX)"
cleanup() {
    echo "Räume auf: $WORKDIR"
    rm -rf "$WORKDIR"
}
trap cleanup EXIT

FAKE_HOME="$WORKDIR/home"
PREFS_DIR="$FAKE_HOME/.fakturama2/.metadata/.plugins/org.eclipse.core.runtime/.settings"
mkdir -p "$PREFS_DIR" "$WORKDIR/documents"

# Java .properties escaping, same convention as fakturama-demo.sh's generated body.
WEBBROWSER_URL_ESCAPED="${WEBBROWSER_URL//:/\\:}"
WEBBROWSER_URL_ESCAPED="${WEBBROWSER_URL_ESCAPED//=/\\=}"

{
    echo "eclipse.preferences.version=1"
    echo "isreinit=false"
    echo "jdbc_reconnect=true"
    echo "jakarta.persistence.jdbc.driver=org.mariadb.jdbc.Driver"
    printf 'jakarta.persistence.jdbc.url=jdbc\\:mariadb\\://%s\\:%s/%s\n' "$DB_HOST" "$DB_PORT" "$DB_NAME"
    printf 'jakarta.persistence.jdbc.user=%s\n' "$DB_USER"
    printf 'jakarta.persistence.jdbc.password=%s\n' "$DB_PASSWORD"
    echo "GENERAL_WORKSPACE=$WORKDIR/documents"
    echo "GENERAL_WEBBROWSER_URL=$WEBBROWSER_URL_ESCAPED"
    echo "BROWSER_ALLOW_INVALID_CERTS=true"
} > "$PREFS_DIR/com.sebulli.fakturama.rcp.prefs"
unset DB_PASSWORD

echo "Starte Fakturama-Demo (DB: ${DB_HOST}:${DB_PORT}/${DB_NAME}) ..."
# -Dfakturama.demoMode=true: see fakturama-demo.sh's identical comment.
"$APP_DIR/Fakturama" -vm "$JRE_DIR/bin/java" -vmargs "-Duser.home=$FAKE_HOME" "-Dfakturama.demoMode=true"

echo "Fakturama beendet."
