#!/usr/bin/env bash
#
# Installed wrapper for the normal (non-demo) Fakturama2 .deb package. App + JRE
# are unpacked under /opt/fakturama2/ once, at package install time. Unlike the
# demo wrapper (see deb-wrapper-template.sh), this runs with the user's real
# $HOME every time - normal, persistent ~/.fakturama2 config across runs, no
# temp workspace, no forced test-DB prefs, no demoMode flag. Whatever a fresh
# Fakturama profile does on its own first launch (e.g. its bundled HSQL
# database) is what a user of this package sees, same as the official
# install4j-built installers.
#
# Generated by build-deb.sh from deb-wrapper-normal-template.sh - not meant to
# be edited by hand on an installed system; rebuild the .deb instead.

set -euo pipefail

APP_DIR="/opt/fakturama2/app"
JRE_DIR="/opt/fakturama2/jre"

exec "$APP_DIR/Fakturama" -vm "$JRE_DIR/bin/java"
